### ISSUE TITLE
ligature not being applied when the characters word-wrap

### ISSUE THREAD

**Issue by UltraSimplified** [i-tu/Hasklig#14]
Full disclosure: I only came across this yesterday in an article on Smashing Magazine's newsletter. It's a brilliant concept and it makes working in code much more visually appealing. I was a bit worried at first that the symbols might diminish the importance of the operator when the page is being scanned but my experience so far is that the opposite is true: they really jump out making the operation much clearer. Good work.

I'm using this font on a Mac in the Coda IDE and I've noticed that if the character pair is interrupted by a word-wrap that the ligature is not applied. Is this a problem with my IDE or can this be addressed within the ligature logic? Also if I resize the screen the ligature is applied correctly.

![ligatures](https://cloud.githubusercontent.com/assets/522171/7960637/f4dec0e0-09f9-11e5-8b50-0be3e6297ba5.png)

**Comment by i-tu** [comment]
This issue is the result of the editor splitting the symbol, and cannot be fixed using the OpenType ligature feature. I suggest asking the developers of Coda to change their word-wrapping algorithm.

(sidenote: I noticed recently that the programming font [Monoid is using the OpenType *contextual alternate* feature](https://github.com/larsenwork/monoid/blob/master/Utilities/Monoid-*.fea#L69) instead of the OpenType ligature feature. This not conventional, but seems to result in subtle differences in rendering, resulting in support for the OSX Terminal and Eclipse, and could have an effect on this issue.)

**Comment by UltraSimplified** [comment]
Thanks, I'll raise it with Panic and see if they can do anything with it. Hopefully they'll apply what you're doing to Panic Sans. I've been using Hasklig for about a month now and it has transformed my experience of coding. It's so much cleaner. 

I looked at Monoid but I prefer the Hasklig font. Monoid seems a bit too condensed.

**Comment by i-tu** [comment]
Thank you for your kind words :)

**Comment by i-tu** [comment]
Closing this issue for now
