### ISSUE TITLE
How to modify Hasklig and apply to other fonts? 

### ISSUE THREAD

**Issue by mcdirmid** [i-tu/Hasklig#37]
I'm interested in adding Hasklig-style ligatures to a proportional font like Source Sans Pro. However, looking at the code for Hasklig/source-sans-pro and instructions for building it, I can't get enough insight in how to do this. I think it would be of great value to the programming community if some information was provided on how Hasklig was developed from an open source font (what tools were used, how it was built, and so on) so that it could be modified and replicated in other contexts.

**Comment by i-tu** [comment]
I have been meaning to write a long blog post about the development of Hasklig. I've been putting it off since it would be DOA due to changes in the process of building Source Code Pro (UFO instead of VFB). 

I'm spending parts of my winter holidays bringing Hasklig up to speed with Source Code Pro. I've had to do some trial and error myself in getting everything right but I should be able to write that long-due post.

In the meantime, perhaps you could mention what is unclear to you? I'm happy to reply to specific questions.

You can get started by downloading ADFKO on your computer. Your first priority should be to get a full build of SCP all the way from masters to instances (light, medium, bold, etc.) and after that from the instances to final OTF files. After that it's a matter of adding your glyphs to the masters and configuration/feature files, and repeating the build.

**Comment by i-tu** [comment]
@mcdirmid , although it doesn't lay this issue to rest, check the new 0.9 release and instructions in Readme.md.

**Comment by mcdirmid** [comment]
@i-tu , looks better, but I don't have a problem with building hasklig (I can follow the build instructions just fine!). My problem is actually starting with a new font from scratch (a proportional font rather than a type writer one), actually doing the glyphs (I've tried and failed with FontForge), and then building. A HOWTO would be useful (so you want to build your own typographically enhanced programming font...).

BTW, Hasklig works fine in Visual Studio 2015, you can probably add that to the list of supported editors (not that anyone is using Haskell with VS, but it works great for C# also).

**Comment by i-tu** [comment]
@mcdirmid , if you really want to start from scratch, don't put the cart before the horse. Fundamentally programming typefaces are no different from other typefaces, and require just as much care and knowledge. Unless you have modest goals, expect a lot of hard work. Look for resources on general type design.

When you have a clear vision, learn the tools. A good font editor makes a big difference. I haven't used FontForge, but a lot of people are saying good things about Glyphs. I used FontLab for Hasklig, but will change to glyphs since it handles UFO better.

After you've created a programming typeface, extending it will come easily.
