### ISSUE TITLE
Square brackets are too light in Medium font

### ISSUE THREAD

**Issue by vasily-kirichenko** [i-tu/Hasklig#76]
![image](https://cloud.githubusercontent.com/assets/873919/18392965/70047410-76bc-11e6-9e21-6a653221ddd7.png)

Compare to Fira Code Medium:

![image](https://cloud.githubusercontent.com/assets/873919/18393079/c8a1c23a-76bc-11e6-901e-9dd032cd9e60.png)

(Atom editor on Windows, 4K resolution)

**Comment by vasily-kirichenko** [comment]
I mean the line width of `[` and `]` is smaller then one of alphabetical chars (not the fact that Fira Code shows [] as a rectangle).

**Comment by i-tu** [comment]
Hasklig is based on Source Code Pro. If you are unhappy with how Hasklig looks in this aspect, you need to file an issue in the [Source Code Pro project](https://github.com/adobe-fonts/source-code-pro) for the change to eventually be merged into Hasklig.

As a side note, I notice you have many different font weights set. Perhaps you can change the weight of brackets from your syntax highlighting definition? Also since the brackets are light blue, they appear thinner than the black symbols.
