### ISSUE TITLE
Bad definition from Windows with ".otf"

### ISSUE THREAD

**Issue by thiagolucio** [i-tu/Hasklig#87]
Is it possible to create a ".ttf" version? 
In Windows (inside Webstorm) this font is very ugly but when I used on Linux this font is great!

**Comment by Kurre** [comment]
Just noticed the same thing (with PhpStorm). If ttf format would fix this issue and it could be provided, I would the very grateful :)

Tried few online otf-2-ttf converters, but no avail.

**Comment by Lugribossk** [comment]
I managed to get the OTF version to work in IntelliJ on Windows by adapting the instructions in http://sticksnglue.com/wordpress/source-code-pro-phpstorm-the-plot-thickens/

I.e. place the files in the Java fonts folder used by IntelliJ (in my case `C:\Users\Bo\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\172.3317.76\jre64\lib\fonts`), rather than in the Windows fonts folder.

**Comment by thiagolucio** [comment]
I create a repository with Hasklig Family font for windows. That's run very well native for all Editors.
https://github.com/thiagolucio/HaskligFontFamily-Windows

Be Happy :)

**Comment by elias102** [comment]
> I create a repository with Hasklig Family font for windows. That's run very well native for all Editors.
> https://github.com/thiagolucio/HaskligFontFamily-Windows
> 
> Be Happy :)

thank you so much man

**Comment by i-tu** [comment]
Can someone check if the ttf fonts included in the latest release work for your use case?
